# Example configuration for AWS Bedrock LLM provider
# Copy this to ~/.aws-cost-cli/config.yaml and customize as needed

llm_provider: bedrock
llm_config:
  provider: bedrock
  model: anthropic.claude-3-haiku-20240307-v1:0  # Claude 3 Haiku model
  region: us-east-1  # AWS region where Bedrock is available
  # profile: production  # Optional: AWS profile to use (uses default if not specified)

# Other configuration options
default_profile: null  # Default AWS profile for cost queries
cache_ttl: 3600  # Cache TTL in seconds (1 hour)
output_format: simple  # Output format: simple, detailed, or json
default_currency: USD

# Alternative Bedrock models you can use:
# - anthropic.claude-3-haiku-20240307-v1:0 (fast, cost-effective)
# - anthropic.claude-3-sonnet-20240229-v1:0 (balanced performance)
# - anthropic.claude-3-opus-20240229-v1:0 (highest capability)
# - amazon.titan-text-express-v1 (Amazon's model)
# - ai21.j2-ultra-v1 (AI21 Labs model)

# Note: Ensure your AWS credentials have the following permissions:
# - bedrock:InvokeModel
# - bedrock:ListFoundationModels (optional, for model discovery)