name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Verify (uv + Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Create venv
        run: uv venv

      - name: Install dev dependencies
        run: . .venv/bin/activate && uv pip install -e .[dev]

      - name: Verify (lint, typecheck, coverage)
        if: ${{ github.event_name != 'pull_request' }}
        run: . .venv/bin/activate && make verify

      - name: Upload coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            .coverage*
            coverage.xml
            htmlcov/**
          if-no-files-found: ignore
